#!/bin/bash

source /root/spark_files/configure_spark.sh

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "WORKER_IP=$IP"

echo "preparing Spark"
prepare_spark $@

echo "Java home: $JAVA_HOME"

echo "starting etcd-service for name resolution"
cd /root/spark_files/etcd-service
python /root/spark_files/etcd-service/main.py --etcd_directory etcd_spark/$1/name_service --etcd_port $ETCD_PORT $ETCD_ADDRESS $HOST_ADDRESS &
cd $SPARK_HOME

echo "starting Hadoop Datanode"
service hadoop-datanode start

echo "starting sshd"
/usr/sbin/sshd

sleep 5

echo "starting Spark Worker"
cp /root/spark_worker_files/run_spark_worker.sh /
chmod a+rx /run_spark_worker.sh
sudo -u hdfs SPARK_WORKER_UI_PORT=$SPARK_WORKER_UI_PORT SPARK_HOME=$SPARK_HOME /run_spark_worker.sh
